name: DiscordRankSync
version: ${project.version}
description: Allow user to link their discord to their minecraft account
author: BebeDlaStreat
main: fr.bebedlastreat.discord.spigot.DiscordSyncSpigot
softdepend: [PlaceholderAPI]

commands:
  link:
    description: Confirm link to your discord account
  unlink:
    description: Unlink from your discord accoun
  claimboost:
    description: Claim boost reward
  stopbot:
    description: Stop the discord bot
    permission: discord.stopbot
    aliases: [stopdiscord]