# support: https://bebedlastreat.fr/discord

bot-token: "token"
guild-id: "0000000000000000000" # id of the discord server the bot should fetch roles
rename: true # rename a user to his minecraft name when he links his account

ranks:
  # warning: when a user unlink his account, he will get removed of all configured roles
  exemple:
    id: "0000000000000000000" # the discord id of the role, need developer mod enabled to get it
    permission: "group.default" # the permission the player should have on minecraft

activity:
  enable: false
  type: "PLAYING" # PLAYING, STREAMING, LISTENING, WATCHING, COMPETING
  message: "DiscordRankSync"

# delay for plugin message/placeholder api refresh
refresh-delay: 30

database: "MariaDB" # Currently only MariaDB is supported but I will include later MongoDB support if it is requested (sql is better for use of this plugin)

reward-command: [] # command executed when a player links his account for the first time (user {player} as placeholder for player name)

boost-reward: [] # command to execute when a player with boost rank execute /claimboost, can be executed every months

join-message-delay: 0 # delay in ticks (50ms) to send the join message, useful when you have a lobby plugin which send a welcome message

date-format: "MM/dd/yy hh:mm aa" # see https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

# Enable it if you put the jar on your spigot servers and you have it running on your proxy. It will prevent bot start and read plugin messages from the proxy. It's useful for PlaceholderAPI.
standalone: false

sql:
  ip: "127.0.0.1"
  port: 3306
  user: "root"
  password: "password"
  database: "discord" # database sould already be created
  table: "discord_sync" # the table of the table used to store, automatically created
  properties: "?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8"

# warning: no legacy color support, you must use minimessage format: https://docs.advntr.dev/minimessage/format.html)
messages:
  name: "name" # should not contain a space
  ping-command: "Get bot latency"
  link-command: "Link your Minecraft account on the server"
  link-command-name: "The Minecraft account username you want to link"
  unlink-command: "Unlink your Discord account from your Minecraft account"
  minecraft-command: "Get the Minecraft account linked to a Discord account"
  minecraft-command-name: "The Discord account"
  discord-command: "Get the Discord account linked to a Minecraft account"
  discord-command-name: "The Minecraft account username"

  no-minecraft: "No Minecraft account found for this identifier"
  results: "Results: "
  no-discord: "No Discord account found for this username"
  error: "Error"
  already-link-minecraft: "This Discord account is already linked to a Minecraft account"
  not-online: "This player is not online"
  already-link-discord: "This Minecraft account is already linked to a Discord account"
  validation: "Validation"
  validation-desc: "To confirm the link between your Discord and Minecraft accounts, use\n`/link {id}`"
  no-link-minecraft: "This Discord account is not linked to a Minecraft account"
  success: "Success"
  success-desc: "Your Discord account has been successfully unlinked from your Minecraft account"

  link-usage: "<gradient:#fb0000:#0028fd>Usage: /link <code></gradient>"
  you-already-link: "<red>Your Minecraft account is already linked to a Discord account.</red>"
  link-success: "<green>Your Minecraft account has been successfully linked to your Discord account!\nTo receive your Discord roles, simply log out and log back in.</green>"
  invalid-code: "<rainbow>Invalid code!</rainbow>"
  no-link: "<red>You haven't attempted to link your Minecraft account to your Discord account in the last 5 minutes.</red>"
  not-linked: "<red>Your Minecraft account is not linked to a Discord account.</red>"
  unlink-success: "<green>Your Minecraft account has been successfully unlinked from your Discord account!</green>"
  stop-bot: "You just stopped the bot!"

  join-message: "" # a message sent to unlinked players on join, let it empty for no join message

  not-boosting: "<red>You need to boost our discord server to claim this reward</red>"
  boost-countdown: "<red>You already claim your reward this month, please wait until {date}</red>"
  boost-claim: "<green>You successfully claimed your boost reward</green>"

  papi-not-linked: "Not linked"